#Header for alert
alertHeader: '&c[Alert] 
#Style for the current server in /server {CURRENTSERVER} is the current server
currentserver: '&fYou are currently connected to: &6{CURRENTSERVER}'
#Style for the server list in /server {SERVERLIST} is the list of servers
serverlist: '&fYou can connect to the following servers: &6{SERVERLIST}'
#Style for the commas in the serverlist of /server {SERVERLIST}
commacolor: '&f, &6'
#The message if a server does not exist
dnemessage: '&cThe specified server does not exist.'
#The message if a player tries to connect to a whitelisted server, {SERVERNAME} is the name of the server they are connecting to
whitelistedserver: '&cKicked whilst connecting to {SERVERNAME}: &fYou are not whitelisted on this server!'
#The message if a player tries to connect to a full server, {SERVERNAME} is the name of the server they are connecting to
#The permission lilyutils.fullserver Allows players to connect to full servers (they must have some permission on that server 
#to be able to connect such as essentials.joinfullserver).
fullserver: '&cKicked whilst connecting to {SERVERNAME}: &fThe server is full!'
#The message if a player tries to connect to a server they are banned on, {SERVERNAME} is the name of the server they are connecting to
playerbanned: '&cKicked whilst connecting to {SERVERNAME}: &fYou are banned from this server.'
#The message before /glist is executed (put none for none)
beforeglist: 'none'
#The styling of /glist {SERVERNAME} for the servers name, {SERVERCOUNT} for the players online of that server, {PLAYERLIST} for the list of players
gliststyle: '&a[{SERVERNAME}] &e({SERVERCOUNT}): &r{PLAYERLIST}'
#The message before totalonline is sent to the player (put none for none)
beforetotal: 'none'
#The styling of the total players online message after /glist, {TOTAL} for the number
totalonline: '&fTotal players online: {TOTAL}'
#The message after totalonline is sent to the player (put none for none)
aftertotal: 'none'
#The message if a server is offline
serveroffline: '&cThe specified server is currently offline.'
#The message if a player tries connecting to a server they are already on
alreadyonline: '&cYou are already connected to this server!'